# Generated by Django 4.0.1 on 2022-01-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qusition_type',
            new_name='qustion_type',
        ),
    ]
