# Generated by Django 4.0.1 on 2022-01-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_qusition_type_question_qustion_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion_type',
            new_name='question_type',
        ),
    ]
